  user_preferences:
    fixed_digest_emails:
      default: false
      client: true
    fixed_digest_deliveries:
      type: list
      default: '0900|1600'
      client: true
      choices:
        - '0800'
        - '0900'
        - '1000'
        - '1100'
        - '1200'
        - '1300'
        - '1400'
        - '1500'
        - '1600'
        - '1700'
  email:
    fixed_digest_enabled:
      default: true
      client: true